### PR TITLE
Adds Home assistant 

### PR DESCRIPTION
**Pull request by purepani**
Adds a package for home assistant based on https://github.com/Mic92/dream2nix-home-assistant.

### CODE REVIEW

**Comment by purepani** [comment]
Rebased on https://github.com/nix-community/dreampkgs/pull/25 to fix gpt-engineer

**Comment by phaer** [comment]
@purepani Sorry, I must have missed this. Could you rebase/update once again? Then I am happy to merge :)

**Comment by purepani** [comment]
Sure I'll try and do it after I finish work today.

**Comment by purepani** [comment]
There's some dependacy in pygatt that didn't seem to be compatible with 3.12 so it wasn't a quick upgrade. I'll look into it tomorrow

**Comment by purepani** [comment]
Ok @phaer it builds now.

**Comment by purepani** [comment]
@phaer just a quick ping again :)

**Pull request merged**
