### PR TITLE
add nodejs & darwin

### PR DESCRIPTION
**Pull request by happysalada**
this attempts at adding an app, however there still seems to be a problem with darwin. I've created an issue.
https://github.com/nix-community/dreampkgs/issues/11

### CODE REVIEW

**Comment by happysalada** [comment]
@DavHau let me know if that works for you

**Comment by DavHau** [comment]
The changes look good, but the build of ratel fails. Could you add [overrides to dream2nix](https://github.com/nix-community/dream2nix/blob/main/overrides/nodejs/default.nix) to fix the build?

**Comment by happysalada** [comment]
I'm building on darwin and it does build for me. Could you share the failure that you get ?
(if you don't have time, no worries, I should have time to test a linux machine in a week or so)]

**Comment by happysalada** [comment]
added the override to make the build succeed in https://github.com/nix-community/dream2nix/pull/193
it's not the best override, but I would say we merge this for now and revisit later.
happy to take feedback though!

**Comment by DavHau** [comment]
The build doesn't seem to produce an executable. How to test this app?

**Pull request closed without merging**
